### ISSUE TITLE
v5.0.0 has an error to include yetch-polyfill

### ISSUE THREAD

**Issue by nightire** [ember-cli/ember-fetch#118]
Upgrade to v5.0.0 recently and found there was an error:

``` plain
=================================================================================

ENV Summary:

  TIME: Sat Jun 23 2018 11:48:25 GMT+0800 (CST)
  TITLE: ember
  ARGV:
  - /usr/local/bin/node
  - /Users/nightire/Code/choice-form/os-client/node_modules/.bin/ember
  - serve
  - --ssl
  EXEC_PATH: /usr/local/bin/node
  TMPDIR: /var/folders/9_/y4f4n_cd5ddbzftt3x0rz19w0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin
  - /Users/nightire/Code/choice-form/os-client/node_modules/.bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /Users/nightire/.rbenv/shims
  - /Users/nightire/.cargo/bin
  - /Users/nightire/.config/yarn/global/node_modules/.bin
  - /usr/local/opt/gnu-tar/libexec/gnubin
  - /usr/local/Cellar/zplug/2.4.2/bin
  - /usr/local/opt/zplug/bin
  - /usr/local/sbin
  PLATFORM: darwin x64
  FREEMEM: 55902208
  TOTALMEM: 17179869184
  UPTIME: 393513
  LOADAVG: 5.244140625,3.9296875,2.80859375
  CPUS:
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.8.0
  - icu: 60.1
  - modules: 57
  - napi: 3
  - nghttp2: 1.29.0
  - node: 8.11.2
  - openssl: 1.0.2o
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.19.1
  - v8: 6.2.414.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: ENOTDIR: not a directory, lstat '/Users/nightire/Code/choice-form/os-client/node_modules/yetch/dist/yetch-polyfill.js/yetch-polyfill.js'
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: ENOTDIR: not a directory, lstat '/Users/nightire/Code/choice-form/os-client/node_modules/yetch/dist/yetch-polyfill.js/yetch-polyfill.js'
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: ENOTDIR: not a directory, lstat '/Users/nightire/Code/choice-form/os-client/node_modules/yetch/dist/yetch-polyfill.js/yetch-polyfill.js'

=================================================================================
```

**Comment by xg-wang** [comment]
@nightire I tried a fresh `ember new xxx; ember install ember-fetch` and it's working for me. Can you share your package.json or a repro?

**Comment by nightire** [comment]
@xg-wang yes, a repro is: https://github.com/choice-form/os-client

**Comment by nightire** [comment]
`npm cache clean --force` solve this issue.

**Comment by nightire** [comment]
@xg-wang Hi, me again. I found this issue is back and it is becoming more complex than last time.

Yesterday I was following [this article](http://www.oligriffiths.com/2018/07/17/ember-cli-broccoli-2/) to experiment with broccoli 2, I see this error again. Then I did `npm cache clean --force` but it didn't help like before.

I list the files under `node_modules/yetch/dist` and I found there actually has a `yetch-polyfill.js` file, that got me confused, I cannot figure out how this error been caused. Do you have any ideas?

![image](https://user-images.githubusercontent.com/1104018/42862648-021d3ddc-8a93-11e8-9542-8cf2b9381d24.png)
![image](https://user-images.githubusercontent.com/1104018/42862661-1741d60a-8a93-11e8-854f-c8bc501eace0.png)
![image](https://user-images.githubusercontent.com/1104018/42862673-23015862-8a93-11e8-8790-61ca935c901e.png)

full error log:

``` plain
=================================================================================

ENV Summary:

  TIME: Wed Jul 18 2018 13:53:05 GMT+0800 (CST)
  TITLE: ember
  ARGV:
  - /usr/local/bin/node
  - /usr/local/bin/ember
  - serve
  EXEC_PATH: /usr/local/bin/node
  TMPDIR: /var/folders/3f/kf4xv_5d1qg24tzgc4kl5h6h0000gn/T
  SHELL: /usr/local/bin/zsh
  PATH:
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/opt/texinfo/bin
  - /usr/local/opt/sqlite/bin
  - /usr/local/opt/openssl/bin
  - /usr/local/opt/libxml2/bin
  - /usr/local/opt/gettext/bin
  - /usr/local/opt/curl/bin
  - /Users/nightire/.cargo/bin
  - /usr/local/opt/gnu-tar/libexec/gnubin
  - /usr/local/Cellar/zplug/2.4.2/bin
  - /usr/local/sbin
  PLATFORM: darwin x64
  FREEMEM: 1717657600
  TOTALMEM: 17179869184
  UPTIME: 3152
  LOADAVG: 5.205078125,5.7529296875,4.77587890625
  CPUS:
  - Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz - 3300
  - Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz - 3300
  - Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz - 3300
  - Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz - 3300
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.8.0
  - icu: 60.1
  - modules: 57
  - napi: 3
  - nghttp2: 1.32.0
  - node: 8.11.3
  - openssl: 1.0.2o
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.19.1
  - v8: 6.2.414.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Not a directory: /Users/nightire/Code/choice-form/bts-reports/node_modules/yetch/dist/yetch-polyfill.js
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Not a directory: /Users/nightire/Code/choice-form/bts-reports/node_modules/yetch/dist/yetch-polyfill.js
  - name: BuilderError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: BuilderError: Not a directory: /Users/nightire/Code/choice-form/bts-reports/node_modules/yetch/dist/yetch-polyfill.js
    at Builder.checkInputPathsExist (/Users/nightire/Code/choice-form/bts-reports/node_modules/broccoli/lib/builder.js:264:15)
    at new Builder (/Users/nightire/Code/choice-form/bts-reports/node_modules/broccoli/lib/builder.js:65:10)
    at Builder.setupBroccoliBuilder (/Users/nightire/Code/choice-form/bts-reports/node_modules/ember-cli/lib/models/builder.js:81:20)
    at new Builder (/Users/nightire/Code/choice-form/bts-reports/node_modules/ember-cli/lib/models/builder.js:33:10)
    at ServeTask.run (/Users/nightire/Code/choice-form/bts-reports/node_modules/ember-cli/lib/tasks/serve.js:24:55)
    at Promise.resolve.then (/Users/nightire/Code/choice-form/bts-reports/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/nightire/Code/choice-form/bts-reports/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/nightire/Code/choice-form/bts-reports/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/nightire/Code/choice-form/bts-reports/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)

=================================================================================
```

**Comment by nightire** [comment]
And BTW, if I run `ember serve` without broccoli 2, this error will disappear and server will run normally.

**Comment by rwjblue** [comment]
> I list the files under node_modules/yetch/dist path and I found there actually has a yetch-polyfill.js file, that got me confused, I cannot figure out how this error been caused. Do you have any ideas?

Seems like the error is specifically saying that `node_modules/yetch/dist/yetch_polyfill.js` is _not_ a directory (I'm assuming it is instead a file).  Can you confirm?

I suspect that something is trying to treat this path as a directory and this error is thrown by Broccoli 2.0 as it tries to watch directories that are not existing...

**Comment by nightire** [comment]
@rwjblue yes, I can confirm it's a file.

**Comment by rwjblue** [comment]
I suspect the issue is here:

https://github.com/ember-cli/ember-fetch/blob/80e77c832264f84e25f3c2583153ca62f93be1ee/index.js#L122-L131

I'd need to dig in further, but we should probably replace the `find` with a simpler funnel (I suspect that will fix it).

**Comment by xg-wang** [comment]
@rwjblue My PR has changed this part, which should be ready to be merged soon.

**Comment by xg-wang** [comment]
@nightire Can you add repro steps? I'm on your develop branch and `EMBER_CLI_BROCCOLI_2=true EMBER_CLI_SYSTEM_TEMP=true ember s` has no error.

**Comment by nightire** [comment]
@xg-wang yes, I was doing it all over again on my local machine, here is the full process and results:

``` bash
14:19:40 in bts-reports on ⋆develop via ⬢ v8.11.3 and  3.3.0 took 3s
λ npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.

14:20:09 in bts-reports on ⋆develop via ⬢ v8.11.3 and  3.3.0 took 3s
λ rm -fr node_modules tmp dist package-lock.json && npm install
npm WARN deprecated exists-sync@0.0.4: Please replace with usage of fs.existsSync
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

> fsevents@1.2.4 install /Users/nightire/Code/choice-form/bts-reports/node_modules/fsevents
> node install

[fsevents] Success: "/Users/nightire/Code/choice-form/bts-reports/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> swiper@4.3.3 postinstall /Users/nightire/Code/choice-form/bts-reports/node_modules/swiper
> node -e "console.log('\u001b[35m\u001b[1mLove Swiper? Support Vladimir\'s work by donating or pledging on patreon:\u001b[22m\u001b[39m\n > \u001b[32mhttps://patreon.com/vladimirkharlampidi\u001b[0m\n')"

Love Swiper? Support Vladimir's work by donating or pledging on patreon:
 > https://patreon.com/vladimirkharlampidi


> spawn-sync@1.0.15 postinstall /Users/nightire/Code/choice-form/bts-reports/node_modules/spawn-sync
> node postinstall

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN babel-plugin-debug-macros@0.2.0-beta.6 requires a peer of @babel/core@^7.0.0-beta.42 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.3 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.
npm WARN cldr-numbers-full@29.0.0 requires a peer of cldr-core@29.0.0 but none is installed. You must install peer dependencies yourself.

added 2806 packages from 1602 contributors and audited 372023 packages in 195.849s
found 36 vulnerabilities (6 low, 22 moderate, 8 high)
  run `npm audit fix` to fix them, or `npm audit` for details

14:23:44 in bts-reports on ⋆develop [!] via ⬢ v8.11.3 and  3.3.0 took 3m 27s
λ npm install --save-dev "https://github.com/ember-cli/ember-cli.git#master"
npm WARN babel-plugin-debug-macros@0.2.0-beta.6 requires a peer of @babel/core@^7.0.0-beta.42 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.3 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.
npm WARN cldr-numbers-full@29.0.0 requires a peer of cldr-core@29.0.0 but none is installed. You must install peer dependencies yourself.

+ ember-cli@3.4.0-beta.1
added 26 packages from 23 contributors, updated 6 packages and audited 375055 packages in 80.515s
found 36 vulnerabilities (6 low, 22 moderate, 8 high)
  run `npm audit fix` to fix them, or `npm audit` for details

14:33:24 in bts-reports on ⋆develop [!] via ⬢ v8.11.3 and  3.4.0-beta.1 took 1m 21s
λ EMBER_CLI_BROCCOLI_2=true EMBER_CLI_SYSTEM_TEMP=true ember serve

WARNING:
WARNING: /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules/tests/dummy-addon:
WARNING:    Missing package directory
WARNING:
WARNING: /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules/tests/dummy-less-addon:
WARNING:    Missing package directory
WARNING:
WARNING: /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules/tests/dummy-sass-addon:
WARNING:    Missing package directory
WARNING: For addon at path /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules:
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-sass-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-less-addon'
WARNING: For addon at path /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules:
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-sass-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-less-addon'
WARNING: For addon at path /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules:
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-sass-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-less-addon'
WARNING: For addon at path /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules:
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-sass-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-less-addon'
WARNING: For addon at path /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules:
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-sass-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-less-addon'
WARNING: For addon at path /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules:
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-sass-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-less-addon'
WARNING: For addon at path /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules:
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-sass-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-less-addon'
WARNING: For addon at path /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules:
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-sass-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-less-addon'
WARNING: For addon at path /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules:
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-sass-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-less-addon'
WARNING: For addon at path /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules:
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-sass-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-less-addon'
WARNING: For addon at path /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules:
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-sass-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-less-addon'
WARNING: For addon at path /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules:
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-sass-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-less-addon'
WARNING: For addon at path /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules:
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-sass-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-less-addon'
WARNING: For addon at path /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules:
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-sass-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-less-addon'
WARNING: For addon at path /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules:
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-sass-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-less-addon'
WARNING: For addon at path /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules:
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-sass-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-less-addon'
WARNING: For addon at path /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules:
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-sass-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-less-addon'
WARNING: For addon at path /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-css-modules:
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-sass-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-less-addon'
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
DEPRECATION: Ember will stop including jQuery by default in an upcoming version. If you wish keep using jQuery in your application explicitly add `@ember/jquery` to your package.json
DEPRECATION: Addon files were detected in `/Users/nightire/Code/choice-form/bts-reports/node_modules/ember-cli-deploy-scp/addon`, but no JavaScript preprocessors were found for `ember-cli-deploy-scp`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-cli-deploy-scp`'s `package.json`.
Not a directory: /Users/nightire/Code/choice-form/bts-reports/node_modules/yetch/dist/yetch-polyfill.js


Stack Trace and Error Report: /var/folders/3f/kf4xv_5d1qg24tzgc4kl5h6h0000gn/T/error.dump.f9dc74009c905d155f3d174318240637.log
```

and the full error report:

``` plain
ENV Summary:

  TIME: Wed Jul 25 2018 14:37:36 GMT+0800 (CST)
  TITLE: ember
  ARGV:
  - /usr/local/bin/node
  - /usr/local/bin/ember
  - serve
  EXEC_PATH: /usr/local/bin/node
  TMPDIR: /var/folders/3f/kf4xv_5d1qg24tzgc4kl5h6h0000gn/T
  SHELL: /usr/local/bin/zsh
  PATH:
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/opt/texinfo/bin
  - /usr/local/opt/sqlite/bin
  - /usr/local/opt/openssl/bin
  - /usr/local/opt/libxml2/bin
  - /usr/local/opt/gettext/bin
  - /usr/local/opt/curl/bin
  - /Users/nightire/.cargo/bin
  - /usr/local/opt/gnu-tar/libexec/gnubin
  - /usr/local/Cellar/zplug/2.4.2/bin
  - /usr/local/sbin
  PLATFORM: darwin x64
  FREEMEM: 645742592
  TOTALMEM: 17179869184
  UPTIME: 190078
  LOADAVG: 1.47412109375,2.3486328125,2.5908203125
  CPUS:
  - Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz - 3300
  - Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz - 3300
  - Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz - 3300
  - Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz - 3300
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.8.0
  - icu: 60.1
  - modules: 57
  - napi: 3
  - nghttp2: 1.32.0
  - node: 8.11.3
  - openssl: 1.0.2o
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.19.1
  - v8: 6.2.414.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Not a directory: /Users/nightire/Code/choice-form/bts-reports/node_modules/yetch/dist/yetch-polyfill.js
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Not a directory: /Users/nightire/Code/choice-form/bts-reports/node_modules/yetch/dist/yetch-polyfill.js
  - name: BuilderError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: BuilderError: Not a directory: /Users/nightire/Code/choice-form/bts-reports/node_modules/yetch/dist/yetch-polyfill.js
    at Builder.checkInputPathsExist (/Users/nightire/Code/choice-form/bts-reports/node_modules/broccoli/lib/builder.js:264:15)
    at new Builder (/Users/nightire/Code/choice-form/bts-reports/node_modules/broccoli/lib/builder.js:65:10)
    at Builder.setupBroccoliBuilder (/Users/nightire/Code/choice-form/bts-reports/node_modules/ember-cli/lib/models/builder.js:81:20)
    at new Builder (/Users/nightire/Code/choice-form/bts-reports/node_modules/ember-cli/lib/models/builder.js:33:10)
    at ServeTask.run (/Users/nightire/Code/choice-form/bts-reports/node_modules/ember-cli/lib/tasks/serve.js:24:55)
    at Promise.resolve.then (/Users/nightire/Code/choice-form/bts-reports/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/nightire/Code/choice-form/bts-reports/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/nightire/Code/choice-form/bts-reports/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/nightire/Code/choice-form/bts-reports/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/nightire/Code/choice-form/bts-reports/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
```

**Comment by xg-wang** [comment]
So 2 issues here.
1. @rwjblue 's assumption is correct, my PR for the `find` part fixed this. @nightire please upgrade to ember-fetch@5.1.1
2. `ember-cli-htmlbars-minifier` is not broccoli 1.0 compatible, I have to remove this.

Closing this, feel free to reopen is you still see the error after upgrading to v5.1.1
