### ISSUE TITLE
Cannot read property 'preferNative' of undefined

### ISSUE THREAD

**Issue by initram** [ember-cli/ember-fetch#133]
I am trying to replace ember-ajax with ember-fetch in an addon I use, but when I do it get the error:
`Cannot read property 'preferNative' of undefined`

content of error dump file can be seen below.
```=================================================================================

ENV Summary:

  TIME: Wed Oct 17 2018 12:56:02 GMT+0200 (Romance Daylight Time)
  TITLE: ember
  ARGV:
  - C:\Program Files\nodejs\node.exe
  - C:\Users\mmi\AppData\Roaming\npm\node_modules\ember-cli\bin\ember
  - build
  EXEC_PATH: C:\Program Files\nodejs\node.exe
  TMPDIR: C:\Users\mmi\AppData\Local\Temp
  SHELL: null
  PATH:
  - C
  - \Users\mmi\Desktop\Cmder_mini\bin;C
  - \Users\mmi\Desktop\Cmder_mini\vendor\conemu-maximus5\ConEmu\Scripts;C
  - \Users\mmi\Desktop\Cmder_mini\vendor\conemu-maximus5;C
  - \Users\mmi\Desktop\Cmder_mini\vendor\conemu-maximus5\ConEmu;C
  - \Program Files (x86)\Common Files\Oracle\Java\javapath;C
  - \Python27\;C
  - \Program Files (x86)\Intel\iCLS Client\;C
  - \Program Files\Intel\iCLS Client\;C
  - \WINDOWS\system32;C
  - \WINDOWS;C
  - \WINDOWS\System32\Wbem;C
  - \WINDOWS\System32\WindowsPowerShell\v1.0\;C
  - \Program Files (x86)\Microsoft SQL Server\80\Tools\Binn\;C
  - \Program Files\Microsoft SQL Server\90\DTS\Binn\;C
  - \Program Files\Microsoft SQL Server\90\Tools\binn\;C
  - \Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C
  - \Program Files (x86)\Microsoft SQL Server\90\DTS\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\90\Tools\Binn\VSShell\Common7\IDE\;C
  - \Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE\PrivateAssemblies\;C
  - \Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C
  - \Program Files\Microsoft SQL Server\110\Tools\Binn\;C
  - \dev\Development\Tools\Nant\nant-0.92\bin;c
  - \Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C
  - \Program Files\Microsoft\Web Platform Installer\;C
  - \Program Files\Microsoft SQL Server\120\Tools\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C
  - \Program Files\Microsoft SQL Server\120\DTS\Binn\;C
  - \Program Files\Microsoft SQL Server\130\Tools\Binn\;C
  - \Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C
  - \Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C
  - \Program Files\Intel\Intel(R) Management Engine Components\DAL;C
  - \Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C
  - \Program Files\Intel\Intel(R) Management Engine Components\IPT;C
  - \Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C
  - \Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C
  - \Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C
  - \Program Files\dotnet\;C
  - \Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C
  - \Program Files\nodejs\;C
  - \WINDOWS\System32\OpenSSH\;C
  - \Program Files (x86)\Common Files\Acronis\VirtualFile\;C
  - \Program Files (x86)\Common Files\Acronis\VirtualFile64\;C
  - \Program Files (x86)\Common Files\Acronis\SnapAPI\;C
  - \Program Files\Git\cmd;C
  - \Program Files\TortoiseHg\;C
  - \Program Files (x86)\Yarn\bin\;C
  - \Users\mmi\.dnx\bin;C
  - \Users\mmi\AppData\Local\Microsoft\WindowsApps;C
  - \Program Files\Microsoft VS Code\bin;C
  - \Users\mmi\AppData\Local\GitHubDesktop\bin;C
  - \Users\mmi\AppData\Roaming\npm;C
  - \Users\mmi\AppData\Local\Microsoft\WindowsApps;C
  - \Users\mmi\AppData\Local\Programs\Microsoft VS Code\bin;C
  - \Users\mmi\AppData\Local\Yarn\bin;C
  - \Program Files\Git\usr\bin;C
  - \Program Files\Git\usr\share\vim\vim74;C
  - \Users\mmi\Desktop\Cmder_mini\
  PLATFORM: win32 x64
  FREEMEM: 4853907456
  TOTALMEM: 17080877056
  UPTIME: 571690.2593529
  LOADAVG: 0,0,0
  CPUS:
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 31.0.1
  - http_parser: 2.7.0
  - icu: 59.1
  - modules: 57
  - nghttp2: 1.25.0
  - node: 8.9.1
  - openssl: 1.0.2m
  - tz: 2017b
  - unicode: 9.0
  - uv: 1.15.0
  - v8: 6.1.534.47
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot read property 'preferNative' of undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot read property 'preferNative' of undefined
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Cannot read property 'preferNative' of undefined
    at Class.treeForVendor (C:\dev\GitHub\ember-cli-new-version\node_modules\ember-fetch\index.js:113:43)
    at Class._treeFor (C:\dev\GitHub\ember-cli-new-version\node_modules\ember-cli\lib\models\addon.js:616:33)
    at Class.treeFor (C:\dev\GitHub\ember-cli-new-version\node_modules\ember-cli\lib\models\addon.js:576:21)
    at addons.reduce (C:\dev\GitHub\ember-cli-new-version\node_modules\ember-cli\lib\models\addon.js:449:26)
    at Array.reduce (<anonymous>)
    at Class.eachAddonInvoke (C:\dev\GitHub\ember-cli-new-version\node_modules\ember-cli\lib\models\addon.js:446:24)
    at Class.treeFor (C:\dev\GitHub\ember-cli-new-version\node_modules\ember-cli\lib\models\addon.js:575:22)
    at project.addons.reduce (C:\dev\GitHub\ember-cli-new-version\node_modules\ember-cli\lib\broccoli\ember-app.js:699:26)
    at Array.reduce (<anonymous>)
    at EmberAddon._addonTreesFor (C:\dev\GitHub\ember-cli-new-version\node_modules\ember-cli\lib\broccoli\ember-app.js:697:32)

=================================================================================
```

You can check out this branch https://github.com/initram/ember-cli-new-version/tree/upgrade-no-jquery

Then run `yarn` and `ember build` to reproduce the error.

I tried to figure out what is going on my self, but I could not figure out if the addon that I am trying to change is doing something really weird that is causing the error or what.

**Comment by rwjblue** [comment]
This error happens when you have an addon that doesn’t call `this._super.included.apply(this, arguments)` and depends on `ember-fetch`. We should absolutely handle this situation better though, and error with an actually helpful message.

**Comment by initram** [comment]
I was trying to upgrade ember-cli-new-version. But I have more or less given up on that. The tests kept failing due to some timing issues. But I guess the add-on could still add the initialization.

**Comment by mydea** [comment]
This is not working for me as well, with an engine.

Setup:

```
my-app
 - shared-addon
   - ember-fetch
 - my-engine
   - shared-addon
      - ember-fetch
```

The shared addon does correctly call `this._super.included.apply(this, arguments)`.
However, in the `treeForVendor` hook,

```js
const preferNative = this.buildConfig.preferNative;
```

breaks - there is simply no `this.buildConfig`. Before that, the included hook is called twice.
Not even manually adding `ember-fetch` to the devDependencies of the engine works.

I will try to investigate how this could be fixed...

**Comment by xg-wang** [comment]
Seems this issue shouldn't be closed by https://github.com/ember-cli/ember-fetch/pull/172 as people are still having this https://github.com/ember-cli/ember-fetch/issues/200

But seems ember-cli-new-version is the addon that didn't call `included` hook? @initram can you try patch this addon?

**Comment by knownasilya** [comment]
I'll try to fix this in ember-cli-new-version tomorrow. Thanks for catching this.

**Comment by mydea** [comment]
I guess #172 still relies on the `included` hook to run!
